spring.data.mongodb.uri=mongodb+srv://afsar_uddin:afsar12345@cluster0.ks103p9.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true